services:
  mongodb:
    image: mongo:latest
    container_name: nebulamoon_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - nebula-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: nebulamoon_backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_USERNAME=root
      - DB_PASSWORD=example
    networks:
      - nebula-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: nebulamoon_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:3001
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    networks:
      - nebula-network

volumes:
  mongodb_data:

networks:
  nebula-network:
    driver: bridge